name: linter
on: push
jobs:
  lint-files:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Nix
        uses: cachix/install-nix-action@v25

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Prepare Nix shell
        run: nix develop -c bash -c ':'

      - name: Lint files
        run: nix develop -c clj-kondo --lint deps.edn --config '{:output {:pattern "::{{level}} file={{filename}},line={{row}},col={{col}}::{{message}}"}}'
