name: tests
on: push
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Nix
        uses: cachix/install-nix-action@v25

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache m2
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: m2-${{ hashFiles('deps.edn') }}

      - name: Cache gitlibs
        uses: actions/cache@v2
        with:
          path: ~/.gitlibs
          key: gitlibs-${{ hashFiles('deps.edn') }}

      - name: Prepare Nix shell
        run: nix develop -c bash -c ':'

      - name: Prepare Clojure dependencies
        run: nix develop -c clojure -A:test -P

      - name: Run tests
        run: nix develop -c clojure -X:test
